### ISSUE TITLE
package step missed in README

### ISSUE THREAD

**Issue by Connoropolous** [holochain-open-dev/community-mutual-credit#11]
Hey @guillemcordoba 

Awesome stuff! I found out about this because of your happ-index PR. 
https://github.com/holochain/happ-index/pull/19/files

Decided to give it a run :)
I noticed the use of the `install_from_file` pattern, was Acorn useful for that?

The one thing that didn't work following the README instructions, which were almost all good, was I needed to build the community-currency DNA. 

At first, when I tried to add a username, I got:
<img width="697" alt="Screen Shot 2020-05-16 at 7 57 37 AM" src="https://user-images.githubusercontent.com/1409121/82119868-dd588d00-974f-11ea-9c51-9129e119e3b1.png">

Then I used 
```shell
nix-shell
cd dnas/community-currency
hc package
```

Then I tried again and it worked.

**Comment by guillemcordoba** [comment]
Hi @Connoropolous ! 

Yes thanks! Actually I wanted to thank you for the Acorn code, it was very very useful to know exactly what steps to do to clone a DNA. I have consolidated the function in the [holochain connection wrapper](https://github.com/uprtcl/js-uprtcl/blob/develop/providers/holochain/src/holochain.connection.ts) I use.

And thanks about this issue! Actually the intended thing is that the compiled dna is actually uploaded to git, to avoid any kind of difference between hc compilations. Will update now.

If you want to try it in holoscape, you can install directly the `bundle.toml` too. Beware that you may not be able to access the actual network though, since right now we don't have any volunteer node active to bridge to the mutual-credit DNA.

**Comment by Connoropolous** [comment]
> Yes thanks! Actually I wanted to thank you for the Acorn code, it was very very useful to know exactly what steps to do to clone a DNA. I have consolidated the function in the [holochain connection wrapper](https://github.com/uprtcl/js-uprtcl/blob/develop/providers/holochain/src/holochain.connection.ts) I use.

very nice! wouldn't it be nice if we could get a single function on the HC conductor side that handled all FIVE steps in one call?
I made some suggestions for improvement here, but now thinking about it again I think it would be nice to just turn it all into one call (without removing the other calls, but just adding one that combines them).
https://github.com/holochain/holochain-rust/issues/2172
Also, you might want to add an explainer comment here, to share why this particular call doesn't use await, and is followed by a timeout.
https://github.com/uprtcl/js-uprtcl/blob/ee774f1dbd321689e697e8ac9640e4d25a11bd67/providers/holochain/src/holochain.connection.ts#L93-L98

> 
> And thanks about this issue! Actually the intended thing is that the compiled dna is actually uploaded to git, to avoid any kind of difference between hc compilations. Will update now.

makes sense. yes the hash changing across system builds is a trick.
> 
> If you want to try it in holoscape, you can install directly the `bundle.toml` too. Beware that you may not be able to access the actual network though, since right now we don't have any volunteer node active to bridge to the mutual-credit DNA.

I'll wait for now, but it is good to see it added there. P.s. the patterns you are coming up with around keeping zomes in repos, using submodules, and micro-service patterns on the UI side are looking great.

**Comment by guillemcordoba** [comment]
> very nice! wouldn't it be nice if we could get a single function on the HC conductor side that handled all FIVE steps in one call?

Yes, and I think they intend to do it in the future, like they had in the proto version if I'm not mistaken. 



> Also, you might want to add an explainer comment here, to share why this particular call doesn't use await, and is followed by a timeout.

You're right... That's a weird behavior and don't know how to best address it, how do you do it on your side?



> P.s. the patterns you are coming up with around keeping zomes in repos, using submodules, and micro-service patterns on the UI side are looking great.

Thanks! One of the goals to push these kinds of experiments is to build them thinking ahead in the future. Trying to code only what we need but so that it'd be reusable in the future. More modules like this are going to come, so if you'd want to reuse them or contribute to them do ping me, we don't have enough docu for that yet but if someone like you needed it I would make this a priority.

**Comment by Connoropolous** [comment]
> > very nice! wouldn't it be nice if we could get a single function on the HC conductor side that handled all FIVE steps in one call?
> 
> Yes, and I think they intend to do it in the future, like they had in the proto version if I'm not mistaken.

Oh, yeah, I would encourage them towards it for sure, if you've heard from someone suggesting that.
> 
> > Also, you might want to add an explainer comment here, to share why this particular call doesn't use await, and is followed by a timeout.
> 
> You're right... That's a weird behavior and don't know how to best address it, how do you do it on your side?

I (for now) forked hc-web-client and made a way to make calls to the conductor have specific timeout durations. For this call, I made the timeout duration short, caught that "error" and just resolved a promise anyways, to move on. Similar to what you did, but I think what you did is cleaner really. 
> 
> > P.s. the patterns you are coming up with around keeping zomes in repos, using submodules, and micro-service patterns on the UI side are looking great.
> 
> Thanks! One of the goals to push these kinds of experiments is to build them thinking ahead in the future. Trying to code only what we need but so that it'd be reusable in the future. More modules like this are going to come, so if you'd want to reuse them or contribute to them do ping me, we don't have enough docu for that yet but if someone like you needed it I would make this a priority.

Now that I am seeing how you're prototyping it, I think I can make sense of that pattern, and maybe follow it on occasion for creating zomes too 👍  so just keep it up. Of course documentation will be critical to getting adoption
